export default defineEventHandler((event) => {
    return {
        products: [
            {
                product: "Macbook Pro 16 inch (2020 ) For Sale",
                serial: "BA9212320",
                id: 1374,
                quantity: 122,
                total: 854.08,
                status: '',
                imageUrl: '',
            },
            {
                product: "Gaming Chair, local pickup only",
                serial: "BA9212320",
                id: 3933,
                quantity: 245,
                total: 943.65,
                status: '',
                imageUrl: '',
            },
            {
                product: "Macbook Air 13 inch(2020 ) For Sale",
                serial: "KH9212924",
                id: 9374,
                quantity: 134,
                total: 779.58,
                status: '',
                imageUrl: '',
            },
            {
                product: "Heimer Miller Sofa (Mint Condition)",
                serial: "SD9212969",
                id: 5560,
                quantity: 26,
                total: 275.43,
                status: '',
                imageUrl: '',
            },
            {
                product: "iPad Pro 2017 Model",
                serial: "012921097",
                id: 6065,
                quantity: 76,
                total: 475.22,
                status: '',
                imageUrl: '',
            },
            {
                product: "Gopro hero 7 (with receipt)",
                serial: "BA9212320",
                id: 4349,
                quantity: 47,
                total: 219.78,
                status: '',
                imageUrl: '',
            },
            {
                product: "Dell Computer Monitor",
                serial: "SD9212969",
                id: 9359,
                quantity: 54,
                total: 105.55,
                status: '',
                imageUrl: '',
            },
            {
                product: "AirPods Pro",
                serial: "SD9212969",
                id: 8829,
                quantity: 132,
                total: 928.41,
                status: '',
                imageUrl: '',
            },
            {
                product: "Playstation 4 Limited Edition",
                serial: "SD9212969",
                id: 5045,
                quantity: 15,
                total: 473.85,
                status: '',
                imageUrl: '',
            },
            {
                product: "DJI Mavic Pro 2",
                serial: "SD9212969",
                id: 3536,
                quantity: 39,
                total: 576.28,
                status: '',
                imageUrl: '',
            },
        ],
    };
});
